#: import BarLayout src.widgets.bar_layout.BarLayout
#: import InfoLayout src.widgets.info_layout.InfoLayout
#: import FloatInput src.widgets.float_input.FloatInput
#: import IntInput src.widgets.int_input.IntInput

<MainWidget>:
    border: [0, 0, 0, 0]
    pos_hint: {'center_x': .5, 'center_y': .5}
    do_default_tab: False
    tab_width: self.width/2
    scroll_type: ["bars"]
    canvas:
        Color:
            rgba: (23/255, 29/255, 37/255, 1)
        Rectangle:
            size: self.size
            pos: self.pos

    TabbedPanelItem:
        text: 'EINSTELLUNGEN'
        GridLayout
            cols: 1
            rows: 3
            HeaderBar

                ActionButton
                    id: save_bttn
                    text: 'Speichern'
                    on_press: root.save_settings_on_press()

                ActionButton
                    id: save_n_load_bttn
                    text: 'Speichern & Laden'
                    on_press: root.save_and_load_settings_on_press()

                ActionButton
                    id: reset_bttn
                    text: 'Zurücksetzen'
                    on_press: root.reset_settings_on_press()

            BoxLayout
                orientation: 'horizontal'
                canvas:
                    Color:
                        rgba: 36/255, 40/255, 47/255, 1
                    Rectangle:
                        size: self.size
                        pos: self.pos
                GridLayout:
                    size_hint_x: None
                    width: 375
                    cols: 1 
                    rows: 5

                    Label
                        size_hint_y: None
                        text_size: self.size
                        padding: 18, 10, 0, 0
                        valign: "center"
                        halign: "left"
                        size_hint: None, None
                        width: 300
                        height: 35
                        text: 'Zahlengenerator'
                        font_size: 20
                        bold: True

                    GridLayout
                        cols: 2
                        rows: 3
                        padding: 5, 5, 5, 5
                        size_hint_y: None
                        col_default_width: 200
                        row_default_height: 40
                        spacing: 5, 1
                        height: 150
                        Label
                            text_size: self.size
                            padding: 15, 0, 0, 0
                            valign: "center"
                            halign: "left"
                            size_hint: None, None
                            width: 150
                            height: 30
                            text: 'Anzahl Elemente'
                        IntInput
                            id: members
                            size_hint: None, None
                            multiline: False
                            height: 30

                        Label
                            text_size: self.size
                            padding: 15, 0, 0, 0
                            valign: "center"
                            halign: "left"
                            size_hint: None, None
                            width: 150
                            height: 30
                            text: 'Untere Grenze'
                        IntInput
                            id: lower_limit
                            size_hint: None, None
                            multiline: False
                            height: 30

                        Label
                            text_size: self.size
                            padding: 15, 0, 0, 0
                            valign: "center"
                            halign: "left"
                            size_hint: None, None
                            width: 150
                            height: 30
                            text: 'Obere Grenze'
                        IntInput
                            id: upper_limit
                            size_hint: None, None
                            multiline: False
                            height: 30

                    Label
                        size_hint_y: None
                        text_size: self.size
                        padding: 18, 5, 0, 0
                        valign: "center"
                        halign: "left"
                        size_hint: None, None
                        width: 300
                        height: 35
                        text: 'Animation'
                        font_size: 20
                        bold: True

                    GridLayout
                        size_hint_y: None
                        cols: 2
                        rows: 3
                        padding: 5, 5, 5, 5
                        col_default_width: 200
                        row_default_height: 40
                        spacing: 5, 1
                        height: 150
                        Label
                            text_size: self.size
                            padding: 15, 0, 0, 0
                            valign: "center"
                            halign: "left"
                            size_hint: None, None
                            width: 150
                            height: 30
                            text: 'Vergleichslänge [s]'
                        FloatInput
                            id: compare_duration
                            size_hint: None, None
                            multiline: False
                            height: 30

                        Label
                            text_size: self.size
                            padding: 15, 0, 0, 0
                            valign: "center"
                            halign: "left"
                            size_hint: None, None
                            width: 150
                            height: 30
                            text: 'Tauschlänge [s]'
                        FloatInput
                            id: switch_duration
                            size_hint: None, None
                            multiline: False
                            height: 30

                        Label
                            text_size: self.size
                            padding: 15, 0, 0, 0
                            valign: "center"
                            halign: "left"
                            size_hint: None, None
                            width: 150
                            height: 30
                            text: 'Pausenlänge [s]'
                        FloatInput
                            id: pause_duration
                            size_hint: None, None
                            multiline: False
                            height: 30

                    Widget
                

                GridLayout:
                    size_hint_x: None
                    width: 275
                    cols: 1 
                    rows: 3

                    Label
                        size_hint_y: None
                        text_size: self.size
                        padding: 18, 10, 0, 0
                        valign: "center"
                        halign: "left"
                        size_hint: None, None
                        width: 300
                        height: 35
                        text: 'Diagrammfarben'
                        font_size: 20
                        bold: True

                    GridLayout
                        cols: 2
                        rows: 6
                        padding: 5, 5, 5, 5
                        size_hint_y: None
                        col_default_width: 50
                        row_default_height: 40
                        spacing: 5, 1
                        height: 150
                        Label
                            text_size: self.size
                            padding: 15, 0, 0, 0
                            valign: "center"
                            halign: "left"
                            size_hint: None, None
                            width: 150
                            height: 30
                            text: 'Hintergrund'
                        Button
                            id: background_color
                            background_normal: ''
                            size_hint: None, None
                            height: 30
                            width: 30
                            canvas.before:
                                Color:
                                    rgba: .5, .5, .5, 1
                                Line:
                                    width: 2
                                    rectangle: self.x, self.y, self.width, self.height

                        Label
                            text_size: self.size
                            padding: 15, 0, 0, 0
                            valign: "center"
                            halign: "left"
                            size_hint: None, None
                            width: 150
                            height: 30
                            text: 'Standard'
                        Button
                            id: passive_color
                            background_normal: ''
                            size_hint: None, None
                            height: 30
                            width: 30
                            canvas.before:
                                Color:
                                    rgba: .5, .5, .5, 1
                                Line:
                                    width: 2
                                    rectangle: self.x, self.y, self.width, self.height

                        Label
                            text_size: self.size
                            padding: 15, 0, 0, 0
                            valign: "center"
                            halign: "left"
                            size_hint: None, None
                            width: 150
                            height: 30
                            text: 'Vergleich'
                        Button
                            id: active_color
                            background_normal: ''
                            size_hint: None, None
                            height: 30
                            width: 30
                            canvas.before:
                                Color:
                                    rgba: .5, .5, .5, 1
                                Line:
                                    width: 2
                                    rectangle: self.x, self.y, self.width, self.height

                        Label
                            text_size: self.size
                            padding: 15, 0, 0, 0
                            valign: "center"
                            halign: "left"
                            size_hint: None, None
                            width: 150
                            height: 30
                            text: 'Tausch'
                        Button
                            id: switch_color
                            background_normal: ''
                            size_hint: None, None
                            height: 30
                            width: 30
                            canvas.before:
                                Color:
                                    rgba: .5, .5, .5, 1
                                Line:
                                    width: 2
                                    rectangle: self.x, self.y, self.width, self.height

                        Label
                            text_size: self.size
                            padding: 15, 0, 0, 0
                            valign: "center"
                            halign: "left"
                            size_hint: None, None
                            width: 150
                            height: 30
                            text: 'Sortiert'
                        Button
                            id: sorted_color
                            background_normal: ''
                            size_hint: None, None
                            height: 30
                            width: 30
                            canvas.before:
                                Color:
                                    rgba: .5, .5, .5, 1
                                Line:
                                    width: 2
                                    rectangle: self.x, self.y, self.width, self.height

                        Label
                            text_size: self.size
                            padding: 15, 0, 0, 0
                            valign: "center"
                            halign: "left"
                            size_hint: None, None
                            width: 150
                            height: 30
                            text: 'Text'
                        Button
                            id: text_color
                            background_normal: ''
                            size_hint: None, None
                            height: 30
                            width: 30
                            canvas.before:
                                Color:
                                    rgba: .5, .5, .5, 1
                                Line:
                                    width: 2
                                    rectangle: self.x, self.y, self.width, self.height

                    Widget

                GridLayout:
                    cols: 1 
                    rows: 10

                    Label
                        size_hint_y: None
                        text_size: self.size
                        padding: 18, 10, 0, 0
                        valign: "center"
                        halign: "left"
                        size_hint: None, None
                        width: 300
                        height: 35
                        text: 'Sortierungsverfahren'
                        font_size: 20
                        bold: True

                    GridLayout
                        id: choice_grid
                        size_hint_y: None
                        cols: 1
                        rows: 6
                        padding: 15, 15, 5, 5
                        col_default_width: 200
                        row_default_height: 40
                        spacing: 2, 2
                        height: 180

                    Widget

            InfoLayout
                width: self.width

    TabbedPanelItem:
        text: 'VISUALISIERER'
        GridLayout
            cols: 1
            rows: 3
            HeaderBar

                Button
                    width: 150
                    size_hint_x: None
                    background_normal: "res/bttn_normal.png"
                    background_disabled_normal: "res/bttn_pressed.png"
                    background_down: "res/bttn_pressed.png"
                    background_disabled_down: "res/bttn_pressed.png"
                    id: load_bttn
                    text: 'Laden'
                    on_press: root.load_on_press()

                Button
                    width: 150
                    size_hint_x: None
                    background_normal: "res/bttn_normal.png"
                    background_disabled_normal: "res/bttn_pressed.png"
                    background_down: "res/bttn_pressed.png"
                    background_disabled_down: "res/bttn_pressed.png"
                    id: start_bttn
                    text: 'Start'
                    on_press: root.start_on_press()
                    disabled: True

                Button
                    width: 150
                    size_hint_x: None
                    background_normal: "res/bttn_normal.png"
                    background_disabled_normal: "res/bttn_pressed.png"
                    background_down: "res/bttn_pressed.png"
                    background_disabled_down: "res/bttn_pressed.png"
                    id: stop_bttn
                    text: 'Stop'
                    on_press: root.stop_on_press()
                    disabled: True

                ActionButton
                    id: previous_bttn
                    width: 50
                    text: '<'
                    on_press: root.previous_on_press()
                    disabled: True

                ActionButton
                    id: next_bttn
                    width: 50
                    text: '>'
                    on_press: root.next_on_press()
                    disabled: True
                
                Label
                    id: sort_label
                    size_hint_x: None
                    width: 220
                    text: 'Sortierungsverfahren'
                    padding: 1, 1, 1, 1
                    halign: "left"
                    valign: "middle"

            BarLayout
                id: bars

            InfoLayout
                width: self.width

<ToggleButton>
    background_normal: "res/bttn_pressed.png"
    background_down: "res/tab_selected.png"

<ActionButton@Button>
    size_hint_x: None
    background_normal: "res/bttn_normal.png"
    background_disabled_normal: "res/bttn_pressed.png"
    background_down: "res/bttn_pressed.png"
    background_disabled_down: "res/bttn_pressed.png"

<HeaderBar@BoxLayout>
    size_hint_y: None
    height: 50
    padding: 2, 1, 2 ,1
    spacing: 1
    canvas:
        Color:
            rgba: 23/255, 29/255, 37/255, 1
        Rectangle:
            size: self.size
            pos: self.pos
        Color:
            rgba: 47/255, 54/255, 65/255, 1
        Rectangle:
            size: (self.width, 2)
            pos: (0, self.y)

<TabbedPanelHeader>
    background_normal: "res/bttn_normal.png"
    background_down: "res/tab_selected.png"
    bold: True

<TextInput>
    foreground_color: 1, 1, 1, 1
    background_color: (70/255, 77/255, 88/255, 1)
    cursor_color: 1, 1, 1, 1