#: import BarLayout src.widgets.bar_layout.BarLayout
#: import InfoLayout src.widgets.info_layout.InfoLayout
#: import FloatInput src.widgets.float_input.FloatInput
#: import IntInput src.widgets.int_input.IntInput

<MainWidget>:
    pos_hint: {'center_x': .5, 'center_y': .5}
    do_default_tab: False
    canvas:
        Color:
            rgb: .15, .15, .15
        Rectangle:
            size: self.size
            pos: self.pos

    TabbedPanelItem:
        text: 'Einstellungen'
        GridLayout
            cols: 1
            rows: 3
            BoxLayout
                size_hint_y: None
                height: 50
                padding: 2, 1, 2 ,1
                spacing: 1
                canvas:
                    Color:
                        rgb: .15, .15, .15
                    Rectangle:
                        size: self.size
                        pos: self.pos
                    Color:
                        rgba: .12, .12, .12, .9
                    Rectangle:
                        size: (self.width, 2)
                        pos: (0, self.y)

                Button
                    id: save_bttn
                    size_hint_x: None
                    width: 150
                    text: 'Speichern'
                    on_press: root.save_settings_on_press()

                Button
                    id: save_n_load_bttn
                    size_hint_x: None
                    width: 150
                    text: 'Speichern & Laden'
                    on_press: root.save_and_load_settings_on_press()

                Button
                    id: reset_bttn
                    size_hint_x: None
                    width: 150
                    text: 'Zurücksetzen'
                    on_press: root.reset_settings_on_press()

            BoxLayout
                orientation: 'horizontal'
                GridLayout:
                    size_hint_x: None
                    width: 400
                    cols: 1 
                    rows: 5

                    Label
                        size_hint_y: None
                        text_size: self.size
                        padding: 18, 10, 0, 0
                        valign: "center"
                        halign: "left"
                        size_hint: None, None
                        width: 300
                        height: 30
                        text: 'Zahlengenerator'
                        font_size: 20
                        bold: True

                    GridLayout
                        cols: 2
                        rows: 3
                        padding: 5, 5, 5, 5
                        size_hint_y: None
                        col_default_width: 200
                        row_default_height: 40
                        spacing: 5, 1
                        height: 150
                        Label
                            text_size: self.size
                            padding: 15, 0, 0, 0
                            valign: "center"
                            halign: "left"
                            size_hint: None, None
                            width: 150
                            height: 30
                            text: 'Anzahl Elemente'
                        IntInput
                            id: members
                            size_hint: None, None
                            multiline: False
                            height: 30

                        Label
                            text_size: self.size
                            padding: 15, 0, 0, 0
                            valign: "center"
                            halign: "left"
                            size_hint: None, None
                            width: 150
                            height: 30
                            text: 'Untere Grenze'
                        IntInput
                            id: lower_limit
                            size_hint: None, None
                            multiline: False
                            height: 30

                        Label
                            text_size: self.size
                            padding: 15, 0, 0, 0
                            valign: "center"
                            halign: "left"
                            size_hint: None, None
                            width: 150
                            height: 30
                            text: 'Obere Grenze'
                        IntInput
                            id: upper_limit
                            size_hint: None, None
                            multiline: False
                            height: 30

                    Label
                        size_hint_y: None
                        text_size: self.size
                        padding: 18, 5, 0, 0
                        valign: "center"
                        halign: "left"
                        size_hint: None, None
                        width: 300
                        height: 30
                        text: 'Animation'
                        font_size: 20
                        bold: True

                    GridLayout
                        size_hint_y: None
                        cols: 2
                        rows: 3
                        padding: 5, 5, 5, 5
                        col_default_width: 200
                        row_default_height: 40
                        spacing: 5, 1
                        height: 150
                        Label
                            text_size: self.size
                            padding: 15, 0, 0, 0
                            valign: "center"
                            halign: "left"
                            size_hint: None, None
                            width: 150
                            height: 30
                            text: 'Vergleichslänge [s]'
                        FloatInput
                            id: compare_duration
                            size_hint: None, None
                            multiline: False
                            height: 30

                        Label
                            text_size: self.size
                            padding: 15, 0, 0, 0
                            valign: "center"
                            halign: "left"
                            size_hint: None, None
                            width: 150
                            height: 30
                            text: 'Tauschlänge [s]'
                        FloatInput
                            id: switch_duration
                            size_hint: None, None
                            multiline: False
                            height: 30

                        Label
                            text_size: self.size
                            padding: 15, 0, 0, 0
                            valign: "center"
                            halign: "left"
                            size_hint: None, None
                            width: 150
                            height: 30
                            text: 'Pausenlänge [s]'
                        FloatInput
                            id: pause_duration
                            size_hint: None, None
                            multiline: False
                            height: 30

                    Widget
                
                GridLayout:
                    cols: 1 
                    rows: 10

                    Label
                        size_hint_y: None
                        text_size: self.size
                        padding: 18, 10, 0, 0
                        valign: "center"
                        halign: "left"
                        size_hint: None, None
                        width: 300
                        height: 30
                        text: 'Sortierungsverfahren'
                        font_size: 20
                        bold: True

                    GridLayout
                        id: choice_grid
                        size_hint_y: None
                        cols: 1
                        rows: 6
                        padding: 15, 15, 5, 5
                        col_default_width: 200
                        row_default_height: 40
                        spacing: 2, 2
                        height: 180

                    Widget

            InfoLayout
                width: self.width

    TabbedPanelItem:
        text: 'Visualisierer'
        GridLayout
            cols: 1
            rows: 3
            BoxLayout
                size_hint_y: None
                height: 50
                padding: 2, 1, 2 ,1
                spacing: 1
                canvas:
                    Color:
                        rgb: .15, .15, .15
                    Rectangle:
                        size: self.size
                        pos: self.pos
                    Color:
                        rgba: .12, .12, .12, .9
                    Rectangle:
                        size: (self.width, 2)
                        pos: (0, self.y)

                Button
                    id: load_bttn
                    size_hint_x: None
                    width: 150
                    text: 'Laden'
                    on_press: root.load_on_press()

                Button
                    id: start_bttn
                    size_hint_x: None
                    width: 150
                    text: 'Start'
                    on_press: root.start_on_press()
                    disabled: True

                Button
                    id: stop_bttn
                    size_hint_x: None
                    width: 150
                    text: 'Stop'
                    on_press: root.stop_on_press()
                    disabled: True

                Button
                    id: previous_bttn
                    size_hint_x: None
                    width: 50
                    text: '<'
                    on_press: root.previous_on_press()
                    disabled: True

                Button
                    id: next_bttn
                    size_hint_x: None
                    width: 50
                    text: '>'
                    on_press: root.next_on_press()
                    disabled: True
                
                Label
                    id: sort_label
                    size_hint_x: None
                    width: 220
                    text: 'Sortierungsverfahren'
                    padding: 1, 1, 1, 1
                    halign: "left"
                    valign: "middle"

            BarLayout
                id: bars

            InfoLayout
                width: self.width
