#: include src/kv/components.kv

<MainWidget>:
    border: [0, 0, 0, 0]
    pos_hint: {'center_x': .5, 'center_y': .5}
    do_default_tab: False
    tab_width: self.width/3
    scroll_type: ["bars"]
    canvas:
        Color:
            rgba: header_color
        Rectangle:
            size: self.size
            pos: self.pos

    TabbedPanelItem:
        text: 'EINSTELLUNGEN'
        GridLayout:
            cols: 1
            rows: 3

            HeaderBar:
                ActionButton:
                    id: save_bttn
                    text: 'Speichern'
                    on_press: root.save_settings_on_press()

                ActionButton:
                    id: save_n_load_bttn
                    text: 'Speichern & Laden'
                    on_press: root.save_and_load_settings_on_press()

                ActionButton:
                    id: reset_bttn
                    text: 'Zurücksetzen'
                    on_press: root.reset_settings_on_press()

            GridLayout:
                cols: 2
                rows: 1
                GridLayout:
                    cols: 1
                    rows: 2
                    size_hint_x: None
                    width: 200
                    canvas:
                        Color: 
                            rgba: side_panel_color
                        Rectangle:
                            size: self.size
                            pos: self.pos

                    Label:
                        size_hint_y: None
                        text: 'EINSTELLUNGEN'
                        padding: 0, 5, 0, 0
                        height: 60
                        color: selected_color
                        bold: True
                        font_size: 18

                    BoxLayout:
                        orientation: 'vertical'

                        SettingsToggleButton:
                            state: 'down'
                            text: 'Generator'
                            group: 'Settings'
                            on_press: root.ids['settings_panel'].switch_to(root.ids['generator_tab'])
                        
                        SettingsToggleButton:
                            text: 'Animation'
                            group: 'Settings'
                            on_press: root.ids['settings_panel'].switch_to(root.ids['animation_tab'])
                        
                        SettingsToggleButton:
                            text: 'Farben'
                            group: 'Settings'
                            group: 'Settings'
                            on_press: root.ids['settings_panel'].switch_to(root.ids['colors_tab'])
                        
                        Widget

                TabbedPanel:
                    id: settings_panel
                    border: [0, 0, 0, 0]
                    pos_hint: {'center_x': .5, 'center_y': .5}
                    do_default_tab: False
                    scroll_type: ["bars"]
                    tab_pos: 'left_top'
                    tab_height: 0
                    tab_width: 0
                    canvas:
                        Color:
                            rgba: header_color
                        Rectangle:
                            size: self.size
                            pos: self.pos
                    
                    TabbedPanelItem:
                        id: generator_tab

                        GridLayout:
                            cols: 1 
                            rows: 2
                            padding: 25, 14, 20 ,20
                            canvas:
                                Color: 
                                    rgba: panel_color
                                Rectangle:
                                    size: self.size
                                    pos: self.pos
                            
                            HeaderLabel:
                                text: 'Zahlengenerator'

                            BoxLayout:
                                orientation: 'vertical'
                                padding: 0, 15, 0, 0
                                
                                SettingsGrid:
                                    SettingLabel:
                                        text: 'Anzahl Elemente'

                                    IntInput:
                                        id: numbers_length

                                SettingsGrid:
                                    SettingLabel:
                                        text: 'Untere Grenze'

                                    IntInput:
                                        id: numbers_lower_limit

                                SettingsGrid:
                                    SettingLabel:
                                        text: 'Obere Grenze'

                                    IntInput:
                                        id: numbers_upper_limit

                                Widget

                    TabbedPanelItem:
                        id: animation_tab
                        GridLayout:
                            cols: 1 
                            rows: 2
                            padding: 25, 14, 20 ,20
                            canvas:
                                Color: 
                                    rgba: panel_color
                                Rectangle:
                                    size: self.size
                                    pos: self.pos

                            HeaderLabel:
                                text: 'Animation'

                            BoxLayout:
                                orientation: 'vertical'
                                padding: 0, 15, 0, 0
                                SettingsGrid:
                                    SettingLabel:
                                        text: 'Vergleichslänge [s]'
                                        
                                    FloatInput:
                                        id: duration_compare

                                SettingsGrid:
                                    SettingLabel:
                                        text: 'Tauschlänge [s]'

                                    FloatInput:
                                        id: duration_switch

                                SettingsGrid:
                                    SettingLabel:
                                        text: 'Pausenlänge [s]'

                                    FloatInput:
                                        id: duration_pause

                                Widget
                        

                    TabbedPanelItem:
                        id: colors_tab
                        GridLayout:
                            cols: 1 
                            rows: 3
                            padding: 25, 14, 20 ,20
                            spacing: 0, 15
                            canvas:
                                Color: 
                                    rgba: panel_color
                                Rectangle:
                                    size: self.size
                                    pos: self.pos
                                
                            HeaderLabel:
                                text: 'Diagrammfarben'

                            ScrollView:
                                padding: 0, 30, 0 ,0
                                do_scroll_x: True
                                do_scroll_y: True
                                always_overscroll: False
                                BoxLayout:
                                    orientation: 'vertical'
                                    size_hint_y: None
                                    height: 450
                                    SettingsGrid:
                                        SettingLabel:
                                            text: 'Hintergrund'

                                        ColorButton:
                                            id: color_background

                                    SettingsGrid:
                                        SettingLabel:
                                            text: 'Balken'

                                        ColorButton:
                                            id: color_passive

                                    SettingsGrid:              
                                        SettingLabel:
                                            text: 'Vergleich'

                                        ColorButton:
                                            id: color_active

                                    SettingsGrid:
                                        SettingLabel:
                                            text: 'Tausch'

                                        ColorButton:
                                            id: color_switch

                                    SettingsGrid:
                                        SettingLabel:
                                            text: 'Fertig'

                                        ColorButton:
                                            id: color_sorted

                                    SettingsGrid:
                                        SettingLabel:
                                            text: 'Text'

                                        ColorButton:
                                            id: color_text

                                    Widget

            InfoLayout:
                width: self.width

    TabbedPanelItem:
        text: 'VISUALISIERER'
        GridLayout
            cols: 1
            rows: 3
            HeaderBar:
                EventButton:
                    width: 150
                    id: load_bttn
                    text: 'Neu'
                    on_press: root.load_on_press()

                EventButton:
                    width: 150
                    id: start_bttn
                    text: 'Start'
                    on_press: root.start_on_press()
                    disabled: True

                EventButton:
                    width: 150
                    id: stop_bttn
                    text: 'Stop'
                    on_press: root.stop_on_press()
                    disabled: True

                ActionButton:
                    id: previous_bttn
                    width: 50
                    text: '<'
                    on_press: root.previous_on_press()
                    disabled: True

                ActionButton
                    id: next_bttn
                    width: 50
                    text: '>'
                    on_press: root.next_on_press()
                    disabled: True
                
                Spinner:
                    id: sort_spinner
                    width: 250
                    size_hint_x: None
                    text: 'Bubbblesort'
                    values: 'Bubbblesort'
                    canvas:
                        Color:
                            rgba: selected_color
                        Triangle:
                            points: (self.x+self.width, self.y, self.x+self.width-15, self.y , self.x+self.width, self.y+15)

            BarLayout:
                id: bars

            InfoLayout:
                width: self.width
    
    TabbedPanelItem:
        text: 'SEQUENCE'